name: swifty_chat
description: >-
  A Flutter package to quickly get started building Chat UIs
  with different kind of message kinds.
version: 1.1.2
homepage: https://github.com/EnesKaraosman/swifty_chat
repository: https://github.com/EnesKaraosman/swifty_chat

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.0.0
  dart_extensions: ^2.2.0
  flutter:
    sdk: flutter

  flutter_html: ^2.2.1
  styled_widget: ^0.4.0+3

  swifty_chat_data: ^0.0.2

dev_dependencies:
  flutter_lints: ^1.0.4

  flutter_test:
    sdk: flutter

  swifty_chat_mocked_data:
    path: ./packages/swifty_chat_mocked_data

flutter:
  uses-material-design: true
