name: swifty_chat
description: >-
  A Flutter package to quickly get started building Chat UIs
  with different type of message kinds.
version: 1.5.0
homepage: https://github.com/EnesKaraosman/swifty_chat
repository: https://github.com/EnesKaraosman/swifty_chat

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1

  # https://pub.dev/packages/dart_extensions
  dart_extensions: ^2.2.2

  flutter:
    sdk: flutter

  # https://pub.dev/packages/styled_widget
  flutter_html: ^2.2.1

  # https://pub.dev/packages/styled_widget
  styled_widget: ^0.4.1

  # https://pub.dev/packages/swifty_chat_data
  swifty_chat_data: ^0.1.0

  # https://pub.dev/packages/timeago
  timeago: ^3.4.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.11

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  swifty_chat_mocked_data:
    path: ./packages/swifty_chat_mocked_data

flutter:
  uses-material-design: true
