name: swifty_chat
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.0.0
  dart_extensions: ^2.1.3
  flutter:
    sdk: flutter

  flutter_html: ^2.1.2
  styled_widget: ^0.4.0

  swifty_chat_data:
    path: ./packages/swifty_chat_data

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  swifty_chat_mocked_data:
    path: ./packages/swifty_chat_mocked_data

flutter:
  uses-material-design: true
