name: swifty_chat_mocked_data
description: Contains mock data for the swifty_chat_data package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  faker:

  flutter:
    sdk: flutter

  swifty_chat_data: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/