name: swifty_chat_mocked_data
description: Contains mock data for the swifty_chat_data package.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  faker: ^2.0.0

  flutter:
    sdk: flutter

  swifty_chat_data: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/