name: Flutter build android action
on: [pull_request]
jobs:
  build:
    name: Build Android
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: ⚙️ Install dependencies for all packages
        run: flutter --version && flutter pub get
      - name: ⚙️ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: 'gradle'
        id: java
      - name: 🔨 Build Android app
        run: cd example && flutter build apk
        shell: bash